version: 2

jobs:
  build:
    docker:
      - image: circleci/node:8

      working_directory: ~/monorepo-boilerplate/service-1-nodejs

      steps:
        - checkout
        - run: npm install
        - run: npm test
