version: 2

aliases:
  - &nodejs_build_and_test
      # should be skip if not part of this commit (or not building master)
      - checkout:
          path: ~/monorepo-boilerplate
      - restore_cache:
          keys:
              - v1-dependencies-{{ checksum "package.json" }}
              # fallback to using the latest cache if no exact match is found
              - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: npm test

jobs:

  service-1-nodejs-build:
    docker:
      - image: circleci/node:7.10
    working_directory: ~/monorepo-boilerplate/service-1-nodejs
    steps: *nodejs_build_and_test
  
  service-3-nodejs-build:
    docker:
      - image: circleci/node:7.10
    working_directory: ~/monorepo-boilerplate/service-3-nodejs
    steps: *nodejs_build_and_test

  # TODO: build only folder who has been modified
  build:
      docker:
        - image: circleci/node:7.10
      steps:
          - run: echo "Build !"

  # TODO: deploy only folder who has been modified
  deploy-prod:
      docker:
        - image: circleci/node:7.10
      steps:
          - run: echo "Deploy prod !"

  custom_builder:
      docker:
        - image: circleci/node:7.10
      steps:
          - run: echo "custom_builder!"

  builder:
      name: conditionally run a deploy job
      command: |
        # replace this with your build/deploy check (i.e. current branch is "release")
        if [[ true ]]; then
          curl --user ${CIRCLE_API_USER_TOKEN} \
            --data build_parameters[CIRCLE_JOB]=custom_builder \
            --data revision=$CIRCLE_SHA1 \
            https://circleci.com/api/v1.1/project/github/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME/tree/$CIRCLE_BRANCH
        fi



workflows:
  version: 2
  build:
    jobs:
      - service-1-nodejs-build
      - service-3-nodejs-build
      - builder

      - build:
          filters:
            branches:
              # only from forks
              only: /^pull\/.*$/

      - deploy-prod:
          requires:
            - service-1-nodejs-build
            - service-3-nodejs-build
          filters:
            branches:
                only: master
