version: 2

jobs:
  service-1-nodejs:
    docker:
      - image: circleci/node:7.10

    working_directory: ~/monorepo-boilerplate/service-1-nodejs

    steps:
      - checkout:
          path: ~/monorepo-boilerplate
      - restore_cache:
          keys:
              - v1-dependencies-{{ checksum "package.json" }}
              # fallback to using the latest cache if no exact match is found
              - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: npm test

  deploy:
      docker:
        - image: circleci/node:7.10
      steps:
          - run: echo "Deploy !"

workflows:
  version: 2
  build:
    jobs:
      - service-1-nodejs
